import { selectDiverseActions, type AggregateMetric } from "./domain";
interface Statement { bind(...values: unknown[]): Statement; run(): Promise<unknown>; }
interface Database { prepare(query: string): Statement; }
export interface Env { ENVIRONMENT: "test" | "production"; TEST_CLIENT_IDS: string; A5_HMAC_SECRET?: string; MAX_ACTIONS_PER_CLIENT: string; SEARCH_DB: Database; }
type Run = { request_id:string; idempotency_key:string; correlation_id:string; client_id:string; environment:"test"|"production"; mode:"weekly"|"monthly"; metrics:AggregateMetric[] };
const enc=new TextEncoder(), json=(v:unknown,s=200)=>new Response(JSON.stringify(v),{status:s,headers:{"content-type":"application/json","cache-control":"no-store"}}), record=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==="object"&&!Array.isArray(v), now=()=>new Date().toISOString();
const clients=(e:Env)=>e.TEST_CLIENT_IDS.split(",").map(x=>x.trim());
async function mac(secret:string,v:string){const k=await crypto.subtle.importKey("raw",enc.encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return [...new Uint8Array(await crypto.subtle.sign("HMAC",k,enc.encode(v)))].map(x=>x.toString(16).padStart(2,"0")).join("");}
async function signed(r:Request,e:Env):Promise<unknown|Response>{const raw=await r.text(),t=r.headers.get("x-automation-timestamp"),n=r.headers.get("x-automation-nonce"),s=r.headers.get("x-automation-signature")?.replace(/^sha256[:=]/i,"");if(!e.A5_HMAC_SECRET||!t||!n||!s||Math.abs(Date.now()-Date.parse(t))>300000||s!==await mac(e.A5_HMAC_SECRET,`${t}.${n}.${raw}`))return json({ok:false,error:"INVALID_SIGNATURE"},401);try{await e.SEARCH_DB.prepare("INSERT INTO search_growth_nonces(nonce, expires_at) VALUES(?, ?)").bind(n,Math.floor(Date.now()/1000)+300).run();}catch{return json({ok:false,error:"REPLAY_REJECTED"},409);}try{return JSON.parse(raw);}catch{return json({ok:false,error:"INVALID_JSON"},400);}}
function input(v:unknown,e:Env):Run|Response{if(!record(v)||typeof v.request_id!=="string"||typeof v.idempotency_key!=="string"||typeof v.correlation_id!=="string"||typeof v.client_id!=="string"||!Array.isArray(v.metrics)||v.metrics.length>50||!['weekly','monthly'].includes(v.mode as string))return json({ok:false,error:"INVALID_RUN"},400);if(v.environment!==e.ENVIRONMENT||!clients(e).includes(v.client_id))return json({ok:false,error:"CLIENT_OR_ENVIRONMENT_NOT_ALLOWED"},403);if(v.metrics.some(x=>!record(x)||typeof x.target_page!=="string"||typeof x.family!=="string"||typeof x.current_clicks!=="number"||typeof x.previous_clicks!=="number"||typeof x.impressions!=="number"||typeof x.ctr!=="number"||typeof x.average_position!=="number"||typeof x.sufficient_days!=="boolean"))return json({ok:false,error:"INVALID_AGGREGATES"},400);return v as Run;}
export async function handleRequest(r:Request,e:Env):Promise<Response>{const path=new URL(r.url).pathname;if(r.method==='GET'&&path==='/health')return json({ok:true,data:{service:'arcanium-search-growth',environment:e.ENVIRONMENT,max_actions_per_client:Math.min(Number(e.MAX_ACTIONS_PER_CLIENT)||5,5),llm_enabled:false,provider_spend_enabled:false}});if(r.method!=="POST"||path!=="/v1/run"||!r.headers.get("content-type")?.includes("application/json"))return json({ok:false,error:"NOT_FOUND"},404);const candidate=await signed(r,e);if(candidate instanceof Response)return candidate;const run=input(candidate,e);if(run instanceof Response)return run;const time=now();try{await e.SEARCH_DB.prepare("INSERT INTO search_growth_runs(environment, client_id, idempotency_key, request_id, correlation_id, mode, input_count, action_count, llm_called, provider_spend_enabled, created_at) VALUES(?, ?, ?, ?, ?, ?, ?, 0, 0, 0, ?)").bind(run.environment,run.client_id,run.idempotency_key,run.request_id,run.correlation_id,run.mode,run.metrics.length,time).run();}catch{return json({ok:true,duplicate:true,data:{request_id:run.request_id}},202);}const actions=selectDiverseActions(run.metrics,Math.min(Number(e.MAX_ACTIONS_PER_CLIENT)||5,5));for(const a of actions)await e.SEARCH_DB.prepare("INSERT INTO search_growth_actions(environment, client_id, dedup_key, run_id, action_type, score, confidence, owner_class, manual_review_required, limitations_json, created_at, updated_at) VALUES(?, ?, ?, ?, ?, ?, ?, ?, 1, ?, ?, ?) ON CONFLICT(environment, client_id, dedup_key) DO UPDATE SET run_id=excluded.run_id, score=excluded.score, confidence=excluded.confidence, updated_at=excluded.updated_at").bind(run.environment,run.client_id,a.dedup_key,run.request_id,a.action_type,a.score,a.confidence,a.owner_class,JSON.stringify(a.limitations),time,time).run();await e.SEARCH_DB.prepare("UPDATE search_growth_runs SET action_count=? WHERE environment=? AND client_id=? AND idempotency_key=?").bind(actions.length,run.environment,run.client_id,run.idempotency_key).run();return json({ok:true,data:{request_id:run.request_id,actions,action_count:actions.length,raw_rows_received:false,llm_called:false,provider_spend_enabled:false,automatic_seo_changes:false}},202);}
export default {fetch:(r:Request,e:Env)=>handleRequest(r,e)};
