interface Statement { bind(...values: unknown[]): Statement; run(): Promise<unknown>; }
interface Database { prepare(query: string): Statement; }
export interface Env { ENVIRONMENT: "test" | "production"; TEST_CLIENT_IDS: string; FORM_HMAC_SECRET?: string; ALLOW_EXTERNAL_SEND: "true" | "false"; FORM_DB: Database; }
const encoder = new TextEncoder(); const reply = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { "content-type": "application/json", "cache-control": "no-store" } });
const isRecord = (value: unknown): value is Record<string, unknown> => Boolean(value) && typeof value === "object" && !Array.isArray(value);
const clientAllowed = (env: Env, client: string) => env.TEST_CLIENT_IDS.split(",").map(value => value.trim()).includes(client);
async function sign(secret: string, value: string) { const key = await crypto.subtle.importKey("raw", encoder.encode(secret), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]); return [...new Uint8Array(await crypto.subtle.sign("HMAC", key, encoder.encode(value)))].map(value => value.toString(16).padStart(2, "0")).join(""); }
async function digest(value: string) { return [...new Uint8Array(await crypto.subtle.digest("SHA-256", encoder.encode(value)))].map(byte => byte.toString(16).padStart(2, "0")).join(""); }
async function authenticated(request: Request, env: Env): Promise<unknown | Response> { const raw = await request.text(), timestamp = request.headers.get("x-automation-timestamp"), nonce = request.headers.get("x-automation-nonce"), signature = request.headers.get("x-automation-signature")?.replace(/^sha256[:=]/i, ""); if (!env.FORM_HMAC_SECRET || !timestamp || !nonce || !signature || Math.abs(Date.now() - Date.parse(timestamp)) > 300000 || signature !== await sign(env.FORM_HMAC_SECRET, `${timestamp}.${nonce}.${raw}`)) return reply({ ok: false, error: "INVALID_SIGNATURE" }, 401); try { await env.FORM_DB.prepare("INSERT INTO form_delivery_nonces(nonce, expires_at) VALUES(?, ?)").bind(nonce, Math.floor(Date.now() / 1000) + 300).run(); } catch { return reply({ ok: false, error: "REPLAY_REJECTED" }, 409); } try { return JSON.parse(raw); } catch { return reply({ ok: false, error: "INVALID_JSON" }, 400); } }
export async function handleRequest(request: Request, env: Env): Promise<Response> { const path = new URL(request.url).pathname; if (request.method === "GET" && path === "/health") return reply({ ok: true, data: { service: "arcanium-form-delivery", environment: env.ENVIRONMENT, external_send_enabled: false } }); if (request.method !== "POST" || path !== "/v1/leads" || !request.headers.get("content-type")?.includes("application/json")) return reply({ ok: false, error: "NOT_FOUND" }, 404); const body = await authenticated(request, env); if (body instanceof Response) return body; if (!isRecord(body) || body.environment !== "test" || typeof body.client_id !== "string" || !clientAllowed(env, body.client_id) || typeof body.submission_id !== "string" || typeof body.correlation_id !== "string") return reply({ ok: false, error: "INVALID_LEAD_EVENT" }, 400); const now = new Date().toISOString(); try { await env.FORM_DB.prepare("INSERT INTO lead_delivery_status(environment, client_id, submission_id, correlation_id, payload_hash, status, created_at, updated_at) VALUES(?, ?, ?, ?, ?, 'received', ?, ?)").bind("test", body.client_id, body.submission_id, body.correlation_id, await digest(JSON.stringify(body.payload ?? {})), now, now).run(); } catch { return reply({ ok: true, duplicate: true, data: { submission_id: body.submission_id, status: "received" } }, 202); } return reply({ ok: true, data: { submission_id: body.submission_id, status: "received", delivery_confirmed: false, external_send_enabled: false } }, 202); }
export default { fetch: (request: Request, env: Env) => handleRequest(request, env) };
